import type { Metadata } from 'next';
import '@/fsd/app/styles/globals.css';
import { roboto } from '@/fsd/app/fonts/fonts';
import { oswald } from '@/fsd/app/fonts/fonts';

import { ThemeProvider } from 'next-themes';

// import MyThemeProvider from '@/fsd/app/providers/ThemeProvider/ThemeProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className={`${roboto.variable} ${oswald.variable}`}>
      <body>
        <ThemeProvider enableSystem={false} disableTransitionOnChange defaultTheme="dark">
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
